imports:
    - { resource: "../../vendor/digitalstate/core/src/Ds/Component/Security/Resources/config/security.yml" }

security:
    access_control:
        - { path: ^/cases, role: IS_AUTHENTICATED_FULLY }
