ds_security:
    acl:
        permissions:
            case:               { entity: Ds\Bundle\CaseBundle\Entity\CaseEntity, attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
            case_field:         { field:  Ds\Bundle\CaseBundle\Entity\CaseEntity.*, attributes: [BROWSE, READ, EDIT] }
            case_id:            { field:  Ds\Bundle\CaseBundle\Entity\CaseEntity.id, attributes: [BROWSE, READ, EDIT] }
            case_uuid:          { field:  Ds\Bundle\CaseBundle\Entity\CaseEntity.uuid, attributes: [BROWSE, READ, EDIT] }
            case_created_at:    { field:  Ds\Bundle\CaseBundle\Entity\CaseEntity.createdAt, attributes: [BROWSE, READ, EDIT] }
            case_updated_at:    { field:  Ds\Bundle\CaseBundle\Entity\CaseEntity.updatedAt, attributes: [BROWSE, READ, EDIT] }
            case_deleted_at:    { field:  Ds\Bundle\CaseBundle\Entity\CaseEntity.deletedAt, attributes: [BROWSE, READ, EDIT] }
            case_identity:      { field:  Ds\Bundle\CaseBundle\Entity\CaseEntity.identity, attributes: [BROWSE, READ, EDIT] }
            case_identity_uuid: { field:  Ds\Bundle\CaseBundle\Entity\CaseEntity.identityUuid, attributes: [BROWSE, READ, EDIT] }
            case_owner:         { field:  Ds\Bundle\CaseBundle\Entity\CaseEntity.owner, attributes: [BROWSE, READ, EDIT] }
            case_owner_uuid:    { field:  Ds\Bundle\CaseBundle\Entity\CaseEntity.ownerUuid, attributes: [BROWSE, READ, EDIT] }
            case_title:         { field:  Ds\Bundle\CaseBundle\Entity\CaseEntity.title, attributes: [BROWSE, READ, EDIT] }
