services:
    ds_case.serializer.context_builder.case:
        decorates: api_platform.serializer.context_builder
        class: Ds\Component\Security\Serializer\ContextBuilder\AuthorizationContextBuilder
        arguments:
            - Ds\Bundle\CaseBundle\Entity\CaseEntity
            -
                ROLE_INDIVIDUAL:
                    case_id: [ READ ]
                    case_uuid: [ BROWSE, READ ]
                    case_owner: [ BROWSE, READ ]
                    case_owner_uuid: [ BROWSE, READ ]
                    case_title: [ BROWSE, READ ]
            - "@ds_case.serializer.context_builder.case.inner"
            - "@security.authorization_checker"
