services:
    ds_case.service.case:
        class: Ds\Bundle\CaseBundle\Service\CaseService

    ds_case.service.case_association:
        class: Ds\Bundle\CaseBundle\Service\CaseAssociationService

    ds_case.case.filter:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            - { uuid: exact }
        tags:
            - { name: api_platform.filter, id: ds_case.case.filter }

    ds_case.case_association.filter:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            - { uuid: exact }
        tags:
            - { name: api_platform.filter, id: ds_case.case_association.filter }

    ds_case.doctrine.orm.query_extension.anonymous:
        class: Ds\Component\Security\Doctrine\ORM\QueryExtension\AnonymousExtension
        public: false
        autowire: true
        arguments:
            - Ds\Bundle\CaseBundle\Entity\CaseEntity
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
            - { name: api_platform.doctrine.orm.query_extension.item }

    ds_case.doctrine.orm.query_extension.individual:
        class: Ds\Component\Security\Doctrine\ORM\QueryExtension\IndividualExtension
        public: false
        autowire: true
        arguments:
            - Ds\Bundle\CaseBundle\Entity\CaseEntity
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
            - { name: api_platform.doctrine.orm.query_extension.item }

    ds_case.serializer.context_builder.case:
        decorates: api_platform.serializer.context_builder
        class: Ds\Component\Security\Serializer\ContextBuilder\AuthorizationContextBuilder
        arguments:
            - Ds\Bundle\CaseBundle\Entity\CaseEntity
            -
                ROLE_INDIVIDUAL:
                    case_id: [ READ ]
                    case_uuid: [ BROWSE, READ ]
                    case_owner: [ BROWSE, READ ]
                    case_owner_uuid: [ BROWSE, READ ]
                    case_title: [ BROWSE, READ ]
            - "@ds_case.serializer.context_builder.case.inner"
            - "@security.authorization_checker"
