framework:
    workflows:
        case_state:
            type: state_machine
            marking_store:
                type: single_state
                arguments:
                    - state
            supports:
                - AppBundle\Entity\CaseEntity
            places:
                - open
                - closed
            transitions:
                close:
                    from: open
                    to: closed
                reopen:
                    from: closed
                    to: open

ds_security:
    permissions:
        case:                       { title: app.permissions.case,                        entity:   AppBundle\Entity\CaseEntity,                attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        case_property:              { title: app.permissions.case.property,               property: AppBundle\Entity\CaseEntity.*,              attributes: [BROWSE, READ, EDIT] }
        case_id:                    { title: app.permissions.case.id,                     property: AppBundle\Entity\CaseEntity.id,             attributes: [BROWSE, READ, EDIT] }
        case_uuid:                  { title: app.permissions.case.uuid,                   property: AppBundle\Entity\CaseEntity.uuid,           attributes: [BROWSE, READ, EDIT] }
        case_custom_id:             { title: app.permissions.case.custom_id,              property: AppBundle\Entity\CaseEntity.customId,       attributes: [BROWSE, READ, EDIT] }
        case_created_at:            { title: app.permissions.case.created_at,             property: AppBundle\Entity\CaseEntity.createdAt,      attributes: [BROWSE, READ, EDIT] }
        case_updated_at:            { title: app.permissions.case.updated_at,             property: AppBundle\Entity\CaseEntity.updatedAt,      attributes: [BROWSE, READ, EDIT] }
        case_deleted_at:            { title: app.permissions.case.deleted_at,             property: AppBundle\Entity\CaseEntity.deletedAt,      attributes: [BROWSE, READ, EDIT] }
        case_owner:                 { title: app.permissions.case.owner,                  property: AppBundle\Entity\CaseEntity.owner,          attributes: [BROWSE, READ, EDIT] }
        case_owner_uuid:            { title: app.permissions.case.owner_uuid,             property: AppBundle\Entity\CaseEntity.ownerUuid,      attributes: [BROWSE, READ, EDIT] }
        case_identity:              { title: app.permissions.case.identity,               property: AppBundle\Entity\CaseEntity.identity,       attributes: [BROWSE, READ, EDIT] }
        case_identity_uuid:         { title: app.permissions.case.identity_uuid,          property: AppBundle\Entity\CaseEntity.identityUuid,   attributes: [BROWSE, READ, EDIT] }
        case_title:                 { title: app.permissions.case.title,                  property: AppBundle\Entity\CaseEntity.title,          attributes: [BROWSE, READ, EDIT] }
        case_data:                  { title: app.permissions.case.data,                   property: AppBundle\Entity\CaseEntity.data,           attributes: [BROWSE, READ, EDIT] }
        case_state:                 { title: app.permissions.case.state,                  property: AppBundle\Entity\CaseEntity.state,          attributes: [BROWSE, READ, EDIT] }
        case_statuses:              { title: app.permissions.case.statuses,               property: AppBundle\Entity\CaseEntity.statuses,       attributes: [BROWSE, READ, EDIT] }
        case_version:               { title: app.permissions.case.version,                property: AppBundle\Entity\CaseEntity.version,        attributes: [BROWSE, READ, EDIT] }
        case_status:                { title: app.permissions.case_status,                 entity:   AppBundle\Entity\CaseStatus,                attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        case_status_property:       { title: app.permissions.case_status.property,        property: AppBundle\Entity\CaseStatus.*,              attributes: [BROWSE, READ, EDIT] }
        case_status_id:             { title: app.permissions.case_status.id,              property: AppBundle\Entity\CaseStatus.id,             attributes: [BROWSE, READ, EDIT] }
        case_status_uuid:           { title: app.permissions.case_status.uuid,            property: AppBundle\Entity\CaseStatus.uuid,           attributes: [BROWSE, READ, EDIT] }
        case_status_created_at:     { title: app.permissions.case_status.created_at,      property: AppBundle\Entity\CaseStatus.createdAt,      attributes: [BROWSE, READ, EDIT] }
        case_status_updated_at:     { title: app.permissions.case_status.updated_at,      property: AppBundle\Entity\CaseStatus.updatedAt,      attributes: [BROWSE, READ, EDIT] }
        case_status_deleted_at:     { title: app.permissions.case_status.deleted_at,      property: AppBundle\Entity\CaseStatus.deletedAt,      attributes: [BROWSE, READ, EDIT] }
        case_status_owner:          { title: app.permissions.case_status.owner,           property: AppBundle\Entity\CaseStatus.owner,          attributes: [BROWSE, READ, EDIT] }
        case_status_owner_uuid:     { title: app.permissions.case_status.owner_uuid,      property: AppBundle\Entity\CaseStatus.ownerUuid,      attributes: [BROWSE, READ, EDIT] }
        case_status_identity:       { title: app.permissions.case_status.identity,        property: AppBundle\Entity\CaseStatus.identity,       attributes: [BROWSE, READ, EDIT] }
        case_status_identity_uuid:  { title: app.permissions.case_status.identity_uuid,   property: AppBundle\Entity\CaseStatus.identityUuid,   attributes: [BROWSE, READ, EDIT] }
        case_status_case:           { title: app.permissions.case_status.case,            property: AppBundle\Entity\CaseStatus.case,           attributes: [BROWSE, READ, EDIT] }
        case_status_title:          { title: app.permissions.case_status.title,           property: AppBundle\Entity\CaseStatus.title,          attributes: [BROWSE, READ, EDIT] }
        case_status_description:    { title: app.permissions.case_status.description,     property: AppBundle\Entity\CaseStatus.description,    attributes: [BROWSE, READ, EDIT] }
        case_status_data:           { title: app.permissions.case_status.data,            property: AppBundle\Entity\CaseStatus.data,           attributes: [BROWSE, READ, EDIT] }
        case_status_version:        { title: app.permissions.case_status.version,         property: AppBundle\Entity\CaseStatus.version,        attributes: [BROWSE, READ, EDIT] }
