parameters:
  locale: en

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: ../src/{Controller,Fixture,Repository,Service,Stat,Tenant}

  App\Controller\:
    resource: ../src/Controller
    tags: [controller.service_arguments]

  App\Fixture\:
    resource: ../src/Fixture
    tags: [doctrine.fixture.orm]

  App\Repository\CaseRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\CaseEntity

  App\Repository\CaseStatusRepository:
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - App\Entity\CaseStatus

  App\Stat\CaseEntity\CountStat:
    tags:
      - { name: ds_statistic.stat, alias: case.count }

  App\Stat\CaseEntity\Count\State\ClosedStat:
    tags:
      - { name: ds_statistic.stat, alias: case.count.state.closed }

  App\Stat\CaseEntity\Count\State\OpenStat:
    tags:
      - { name: ds_statistic.stat, alias: case.count.state.open }

  App\Tenant\Loader\AclLoader:
    tags:
      - { name: ds_tenant.loader }

  App\Tenant\Loader\ConfigLoader:
    tags:
      - { name: ds_tenant.loader }

  App\Tenant\Unloader\CaseUnloader:
    tags:
      - { name: ds_tenant.unloader }

  App\Tenant\Unloader\CaseStatusUnloader:
    tags:
      - { name: ds_tenant.unloader, priority: -1 }
